# Describes the format for available alarm control panel services

alarm_disarm:
  description: Send the alarm the command for disarm.
  fields:
    entity_id:
      description: Name of alarm control panel to disarm.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to disarm the alarm control panel with.
      example: 1234

alarm_arm_home:
  description: Send the alarm the command for arm home.
  fields:
    entity_id:
      description: Name of alarm control panel to arm home.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm home the alarm control panel with.
      example: 1234
    ignore_open_sensors:
      description: When True, arm even with active sensors. Default is False
      example: True

alarm_arm_away:
  description: Send the alarm the command for arm away.
  fields:
    entity_id:
      description: Name of alarm control panel to arm away.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm away the alarm control panel with.
      example: 1234
    ignore_open_sensors:
      description: When True, arm even with active sensors. Default is False
      example: True

alarm_arm_night:
  description: Send the alarm the command for arm night.
  fields:
    entity_id:
      description: Name of alarm control panel to arm night.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm night the alarm control panel with.
      example: 1234
    ignore_open_sensors:
      description: When True, arm even with active sensors. Default is False
      example: True
